name: Build Release

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/login-action@v4.2.0
        with:          
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build and Publish
        run:  bash build.sh ${{ vars.DOCKER_USERNAME }} ${{ vars.VITE_API_URL }}